language: objective-c
before_install:
  - wget https://github.com/chrmoritz/starcheat/releases/download/4f7bd31/local_cache.tar.gz
  - unset PYTHONPATH
env:
  secure: "TcFU64a48wQO48pX3zME6b1A0WEhuiGSzfFX4++Y9irxPyvnk9x4PLLbwg2gN6z58GQ68POep9ZD3mcgJVs4VAGEJoxli4wAUCE6VnI/cIl7j98hYw/RoMM4x95r7I07QLL1m2DFBPxlJY9LSqZ+sKd/YoFFTme8oj1UXC0C2oI="
install:
  - sudo tar xf local_cache.tar.gz -C /usr
script:
  - mac/travis.rb
branches:
  only:
    - /^v?(\d)+(\.\d+)*$/
